### ISSUE TITLE
pattern_088? 

### ISSUE THREAD

**Issue by azurelunatic** [tanshoku/squidfingers-patterns#1]
I believe I have found pattern_088 in some places that have other files that match the set. I'm not sure that it's the complete image, but possibly part of it. 

https://ferry-county.com/Images/Wallpaper/pattern_088.gif 
https://www.interplayjazzandarts.org/wp-content/plugins/constant-contact-api/lib/form-designer/patterns/pattern_088.gif
http://style.org.hc360.com/images/detail/mysite/default/pic_3-3-233.gif

**Comment by tanshoku** [comment]
It looks like it is the complete image, since it seems to tile correctly, and is different from all the other ones. I'll add it to the repo soon.Thank you so much for finding it!
